#!/usr/bin/env bash

# Do not use this script manually, Use makefile
set -eu -o pipefail

# Check param or use default
if [[ $# -eq 1 ]]; then
  if [[ $1 == "windows" ]]; then
    export GOOS=windows
    export GOARCH=amd64
  elif [[ $1 == "linux" ]]; then
    export GOOS=linux
    export GOARCH=amd64
  elif [[ $1 == "macos" ]]; then
    export GOOS=darwin
    export GOARCH=amd64
  fi
else
  export GOOS="${GOOS:-$(go env GOHOSTOS)}"
  export GOARCH="${GOARCH:-$(go env GOHOSTARCH)}"
fi

# Define Target name
if [[ $GOOS == "windows" ]]; then
  TARGET="build/steganography-$GOOS-$GOARCH.exe"
elif [[ $GOOS == "darwin" ]]; then
  TARGET="build/steganography-macos"
else
  TARGET="build/steganography-$GOOS-$GOARCH"
fi

export CGO_ENABLED=0
export GOGC=off

echo "Building statically linked $TARGET"
go build -o "${TARGET}" main.go
